name: Check for Python file updates and create pull request

on:
  workflow_dispatch:
  push:
    branches:
      - Testing-branch-2

jobs:
  check-python-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: Testing-branch-2

      - name: Check for Python file update
        id: python-file-changes
        run: |
          if git diff --quiet HEAD~1 HEAD pythonfile_1.py; then
            echo "No changes to Python file."
          else
            echo "Changes detected in Python file."
          fi

      - name: Create pull request
        if: steps.python-file-changes.outputs.return-value != 'No changes to Python file.'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Python file"
          title: "Update Python file"
          body: "Changes detected in Python file. This pull request updates Python file."
          base: Testing-Branch-2
          branch: Main
